import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Shell from "@/components/Shell";
import { SessionProvider } from "@/contexts/SessionContext";
import { StroopProvider } from "@/contexts/StroopContext";
import { InactivityProvider } from "@/contexts/InactivityContext";
import { SubmissionProvider } from "@/contexts/SubmissionContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <StroopProvider>
            <SubmissionProvider>
              <InactivityProvider warningDuration={process.env.SESSION_TIMEOUT_WARNING} logoutDuration={process.env.SESSION_TIMEOUT_LOGOUT}>
                <Shell>
                  {children}
                </Shell>
              </InactivityProvider>
            </SubmissionProvider>
          </StroopProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
